[
  {
    "id" : "a8ef158f-8a7d-4793-94c7-88459e9954d6",
    "prId" : 7400,
    "comments" : [
      {
        "id" : "cf828b97-0076-4877-ad9a-76077794ba87",
        "parentId" : null,
        "author" : {
          "login" : "hurryabit",
          "name" : "Martin Huschenbett",
          "avatarUrl" : "https://avatars0.githubusercontent.com/u/11665611?u=7dbd00d5e7ea53919ed31dc4200f602ebca91c8f&v=4"
        },
        "body" : "If we try to fetch with the wrong type and without proper authorization, which error takes precedence? I would argue the type error should take precedence since it's a static problem.",
        "createdAt" : "2020-09-17T15:48:51Z",
        "updatedAt" : "2020-09-17T15:49:12Z",
        "lastEditedBy" : {
          "login" : "hurryabit",
          "name" : "Martin Huschenbett",
          "avatarUrl" : "https://avatars0.githubusercontent.com/u/11665611?u=7dbd00d5e7ea53919ed31dc4200f602ebca91c8f&v=4"
        },
        "tags" : [
        ]
      },
      {
        "id" : "e00df58f-8185-47b1-aff6-f478d5925ab2",
        "parentId" : "cf828b97-0076-4877-ad9a-76077794ba87",
        "author" : {
          "login" : "nickchapman-da",
          "name" : null,
          "avatarUrl" : "https://avatars1.githubusercontent.com/u/49153372?v=4"
        },
        "body" : "For the fetch itself, this is indeed what occurs: The contract fetch is performed; the contract type is checked against what is expected; and finally the fetch node to be inserted in the transaction is created and authorized.\r\n\r\nBut in the testcase which we modified, the authorization which failed was for the parent exercise of the fetch, which should be performed before the fetch, I believe.",
        "createdAt" : "2020-09-17T16:36:17Z",
        "updatedAt" : "2020-09-17T16:36:18Z",
        "lastEditedBy" : {
          "login" : "nickchapman-da",
          "name" : null,
          "avatarUrl" : "https://avatars1.githubusercontent.com/u/49153372?v=4"
        },
        "tags" : [
        ]
      },
      {
        "id" : "631451e3-d4de-46da-a4df-420d65768211",
        "parentId" : "cf828b97-0076-4877-ad9a-76077794ba87",
        "author" : {
          "login" : "hurryabit",
          "name" : "Martin Huschenbett",
          "avatarUrl" : "https://avatars0.githubusercontent.com/u/11665611?u=7dbd00d5e7ea53919ed31dc4200f602ebca91c8f&v=4"
        },
        "body" : "Yes, the authorization check for the parent exercise should be performed before the `fetch`. Now, I understand what's going on. It all seems to make sense.",
        "createdAt" : "2020-09-17T16:56:46Z",
        "updatedAt" : "2020-09-17T16:56:46Z",
        "lastEditedBy" : {
          "login" : "hurryabit",
          "name" : "Martin Huschenbett",
          "avatarUrl" : "https://avatars0.githubusercontent.com/u/11665611?u=7dbd00d5e7ea53919ed31dc4200f602ebca91c8f&v=4"
        },
        "tags" : [
        ]
      }
    ],
    "commit" : "a360635b966cdfe27bfd3cd6e156308321238660",
    "line" : 6,
    "diffHunk" : "@@ -27,15 +27,15 @@ final class WronglyTypedContractIdIT extends LedgerTestSuite {\n         }\n     })\n \n-  test(\"WTFetchFails\", \"Fetching of the wrong type fails\", allocate(TwoParties))(implicit ec => {\n-    case Participants(Participant(ledger, owner, delegate)) =>\n+  test(\"WTFetchFails\", \"Fetching of the wrong type fails\", allocate(SingleParty))(implicit ec => {"
  }
]