[
  {
    "id" : "3b234c27-ff50-43a2-9849-635f2f718a67",
    "prId" : 5669,
    "comments" : [
      {
        "id" : "a4774e60-9bfb-4bfa-81f3-31ca0d349633",
        "parentId" : null,
        "author" : {
          "login" : "miklos-da",
          "name" : "Miklos",
          "avatarUrl" : "https://avatars0.githubusercontent.com/u/57664299?v=4"
        },
        "body" : "You may want to reference this from `ErrorFactories` instead of hard-coding the same error message.",
        "createdAt" : "2020-04-29T15:40:44Z",
        "updatedAt" : "2020-05-06T07:31:30Z",
        "lastEditedBy" : {
          "login" : "miklos-da",
          "name" : "Miklos",
          "avatarUrl" : "https://avatars0.githubusercontent.com/u/57664299?v=4"
        },
        "tags" : [
        ]
      }
    ],
    "commit" : "d727159f8b35003f5e8fc75af2a53edb62b2b8fc",
    "line" : 114,
    "diffHunk" : "@@ -1,1 +255,259 @@            .validateCommands(api.commands, internal.ledgerTime, internal.submittedAt, None),\n          UNAVAILABLE,\n          \"The ledger configuration is not available.\"\n        )\n      }"
  }
]