[
  {
    "id" : "298fd5cd-bb0e-40bc-9d5b-77fcf1ed3575",
    "prId" : 962,
    "comments" : [
      {
        "id" : "e51b81ca-aab9-43bb-9a16-cbbc7af5630d",
        "parentId" : null,
        "author" : {
          "login" : "neil-da",
          "name" : "Neil Mitchell",
          "avatarUrl" : "https://avatars0.githubusercontent.com/u/35463327?u=0eb1719958bc6e449ec5e7df3a312fa566f5055d&v=4"
        },
        "body" : "If Nix does fail, do we get a failing exit code? Or just continue always now?",
        "createdAt" : "2019-05-07T09:11:12Z",
        "updatedAt" : "2019-05-07T11:14:31Z",
        "lastEditedBy" : {
          "login" : "neil-da",
          "name" : "Neil Mitchell",
          "avatarUrl" : "https://avatars0.githubusercontent.com/u/35463327?u=0eb1719958bc6e449ec5e7df3a312fa566f5055d&v=4"
        },
        "tags" : [
          {
            "value" : "outdated"
          }
        ]
      },
      {
        "id" : "87653209-ec99-421f-943e-6d9ff80ae1f4",
        "parentId" : "e51b81ca-aab9-43bb-9a16-cbbc7af5630d",
        "author" : {
          "login" : "cocreature",
          "name" : "Moritz Kiefer",
          "avatarUrl" : "https://avatars1.githubusercontent.com/u/1313584?u=7864421488a876940b33e865c4b0091925617ca7&v=4"
        },
        "body" : "We don’t look at the exit code but we look at the error message so we don’t always retry.",
        "createdAt" : "2019-05-07T09:12:11Z",
        "updatedAt" : "2019-05-07T11:14:31Z",
        "lastEditedBy" : {
          "login" : "cocreature",
          "name" : "Moritz Kiefer",
          "avatarUrl" : "https://avatars1.githubusercontent.com/u/1313584?u=7864421488a876940b33e865c4b0091925617ca7&v=4"
        },
        "tags" : [
          {
            "value" : "outdated"
          }
        ]
      },
      {
        "id" : "11873ad1-5c80-4f4d-bf67-00450899f50c",
        "parentId" : "e51b81ca-aab9-43bb-9a16-cbbc7af5630d",
        "author" : {
          "login" : "aherrmann-da",
          "name" : "Andreas Herrmann",
          "avatarUrl" : "https://avatars3.githubusercontent.com/u/42969706?v=4"
        },
        "body" : "@cocreature How about something like `if !nix-build ...` or `unset failed; nix-build ... || failed=1` to make sure that we don't silently ignore `nix-build` errors which might cause confusing errors down the line? You can then still check for the log content to decide whether to retry.",
        "createdAt" : "2019-05-07T09:26:04Z",
        "updatedAt" : "2019-05-07T11:14:31Z",
        "lastEditedBy" : {
          "login" : "aherrmann-da",
          "name" : "Andreas Herrmann",
          "avatarUrl" : "https://avatars3.githubusercontent.com/u/42969706?v=4"
        },
        "tags" : [
          {
            "value" : "outdated"
          }
        ]
      },
      {
        "id" : "cec4d847-6f75-49b2-a389-01d86c1aa227",
        "parentId" : "e51b81ca-aab9-43bb-9a16-cbbc7af5630d",
        "author" : {
          "login" : "cocreature",
          "name" : "Moritz Kiefer",
          "avatarUrl" : "https://avatars1.githubusercontent.com/u/1313584?u=7864421488a876940b33e865c4b0091925617ca7&v=4"
        },
        "body" : "Good idea, changed.",
        "createdAt" : "2019-05-07T09:41:53Z",
        "updatedAt" : "2019-05-07T11:14:31Z",
        "lastEditedBy" : {
          "login" : "cocreature",
          "name" : "Moritz Kiefer",
          "avatarUrl" : "https://avatars1.githubusercontent.com/u/1313584?u=7864421488a876940b33e865c4b0091925617ca7&v=4"
        },
        "tags" : [
          {
            "value" : "outdated"
          }
        ]
      }
    ],
    "commit" : "ee2b9c5eaedeac2ffac3764296f4d444e517ea39",
    "line" : null,
    "diffHunk" : "@@ -39,7 +39,7 @@ step \"Building dev-env dependencies\"\n # to make it retry itself. See https://github.com/NixOS/nix/issues/2794 for the issue requesting\n # this feature.\n for i in `seq 10`; do\n-    nix-build nix -A tools -A cached 2>&1 | tee nix_log\n+    nix-build nix -A tools -A cached 2>&1 | tee nix_log || true"
  },
  {
    "id" : "aec6d4fd-dce0-4392-959b-9b668c1e7115",
    "prId" : 962,
    "comments" : [
      {
        "id" : "d465de66-e48d-474c-8e64-6f45adfdc443",
        "parentId" : null,
        "author" : {
          "login" : "neil-da",
          "name" : "Neil Mitchell",
          "avatarUrl" : "https://avatars0.githubusercontent.com/u/35463327?u=0eb1719958bc6e449ec5e7df3a312fa566f5055d&v=4"
        },
        "body" : "I'm sceptical this complexity is worth it. I'd just retry 10 times, stopping on the first success or failing if we require all 10 times. Something as simple as `$A || $A || $A || $A || $A || $A || $A || $A` would make me happier - shell script should be feared.",
        "createdAt" : "2019-05-07T10:07:51Z",
        "updatedAt" : "2019-05-07T11:14:31Z",
        "lastEditedBy" : {
          "login" : "neil-da",
          "name" : "Neil Mitchell",
          "avatarUrl" : "https://avatars0.githubusercontent.com/u/35463327?u=0eb1719958bc6e449ec5e7df3a312fa566f5055d&v=4"
        },
        "tags" : [
        ]
      },
      {
        "id" : "55126a0b-461c-488c-bd52-784d0eff52b7",
        "parentId" : "d465de66-e48d-474c-8e64-6f45adfdc443",
        "author" : {
          "login" : "cocreature",
          "name" : "Moritz Kiefer",
          "avatarUrl" : "https://avatars1.githubusercontent.com/u/1313584?u=7864421488a876940b33e865c4b0091925617ca7&v=4"
        },
        "body" : "If we retry 10 times and have e.g. an actual build failure in GHC, I have to wait for 10 hours until my build actually fails. As much as I dislike shell scripting, I still prefer it over that.",
        "createdAt" : "2019-05-07T11:13:05Z",
        "updatedAt" : "2019-05-07T11:14:31Z",
        "lastEditedBy" : {
          "login" : "cocreature",
          "name" : "Moritz Kiefer",
          "avatarUrl" : "https://avatars1.githubusercontent.com/u/1313584?u=7864421488a876940b33e865c4b0091925617ca7&v=4"
        },
        "tags" : [
        ]
      },
      {
        "id" : "f4ed59b8-3fb8-478d-8b24-e4dba3534d29",
        "parentId" : "d465de66-e48d-474c-8e64-6f45adfdc443",
        "author" : {
          "login" : "neil-da",
          "name" : "Neil Mitchell",
          "avatarUrl" : "https://avatars0.githubusercontent.com/u/35463327?u=0eb1719958bc6e449ec5e7df3a312fa566f5055d&v=4"
        },
        "body" : "You're always in a hurry... Fair enough, that makes sense.",
        "createdAt" : "2019-05-07T11:41:29Z",
        "updatedAt" : "2019-05-07T11:41:30Z",
        "lastEditedBy" : {
          "login" : "neil-da",
          "name" : "Neil Mitchell",
          "avatarUrl" : "https://avatars0.githubusercontent.com/u/35463327?u=0eb1719958bc6e449ec5e7df3a312fa566f5055d&v=4"
        },
        "tags" : [
        ]
      },
      {
        "id" : "6e5b188c-abe4-4e33-9e8f-25736783f234",
        "parentId" : "d465de66-e48d-474c-8e64-6f45adfdc443",
        "author" : {
          "login" : "cocreature",
          "name" : "Moritz Kiefer",
          "avatarUrl" : "https://avatars1.githubusercontent.com/u/1313584?u=7864421488a876940b33e865c4b0091925617ca7&v=4"
        },
        "body" : "I prefer spending my time on more exiting things that build failures :wink: ",
        "createdAt" : "2019-05-07T11:46:45Z",
        "updatedAt" : "2019-05-07T11:46:45Z",
        "lastEditedBy" : {
          "login" : "cocreature",
          "name" : "Moritz Kiefer",
          "avatarUrl" : "https://avatars1.githubusercontent.com/u/1313584?u=7864421488a876940b33e865c4b0091925617ca7&v=4"
        },
        "tags" : [
        ]
      }
    ],
    "commit" : "ee2b9c5eaedeac2ffac3764296f4d444e517ea39",
    "line" : 5,
    "diffHunk" : "@@ -38,13 +38,18 @@ step \"Building dev-env dependencies\"\n # repeat this a few times. There does not seem to be an option that we can pass to nix\n # to make it retry itself. See https://github.com/NixOS/nix/issues/2794 for the issue requesting\n # this feature.\n+NIX_FAILED=0\n for i in `seq 10`; do"
  },
  {
    "id" : "20ac4c6d-982b-4971-8ab7-e65736e2e3de",
    "prId" : 938,
    "comments" : [
      {
        "id" : "a703a07c-bd82-4597-9b09-4d73076fe93a",
        "parentId" : null,
        "author" : {
          "login" : "neil-da",
          "name" : "Neil Mitchell",
          "avatarUrl" : "https://avatars0.githubusercontent.com/u/35463327?u=0eb1719958bc6e449ec5e7df3a312fa566f5055d&v=4"
        },
        "body" : "Why tail the log? Why not just retry 10 times unconditionally. I can imagine lots of flakey errors (connection not available for example), or someone changing the error message. I can't see why trying 10 times on failure would be harmful.",
        "createdAt" : "2019-05-06T12:00:04Z",
        "updatedAt" : "2019-05-06T12:07:03Z",
        "lastEditedBy" : {
          "login" : "neil-da",
          "name" : "Neil Mitchell",
          "avatarUrl" : "https://avatars0.githubusercontent.com/u/35463327?u=0eb1719958bc6e449ec5e7df3a312fa566f5055d&v=4"
        },
        "tags" : [
        ]
      },
      {
        "id" : "8900cc63-aa1c-4a7a-aee7-af452426d947",
        "parentId" : "a703a07c-bd82-4597-9b09-4d73076fe93a",
        "author" : {
          "login" : "cocreature",
          "name" : "Moritz Kiefer",
          "avatarUrl" : "https://avatars1.githubusercontent.com/u/1313584?u=7864421488a876940b33e865c4b0091925617ca7&v=4"
        },
        "body" : "Not harmful but I’d like to know which errors we get and so far I haven’t seen other flaky errors. So I’d prefer an explicit list at least while the number of errors is small (let’s say < 5)",
        "createdAt" : "2019-05-06T12:02:54Z",
        "updatedAt" : "2019-05-06T12:07:03Z",
        "lastEditedBy" : {
          "login" : "cocreature",
          "name" : "Moritz Kiefer",
          "avatarUrl" : "https://avatars1.githubusercontent.com/u/1313584?u=7864421488a876940b33e865c4b0091925617ca7&v=4"
        },
        "tags" : [
        ]
      }
    ],
    "commit" : "53948110e116aab5d089f21b334234773ebe42b7",
    "line" : 14,
    "diffHunk" : "@@ -33,4 +33,17 @@ source dev-env/lib/ensure-nix\n export NIX_CONF_DIR=$PWD/dev-env/etc\n \n step \"Building dev-env dependencies\"\n-nix-build nix -A tools -A cached\n+\n+# Nix cache downloads can sometimes be flaky and end with \"unexpected end-of-file\" so we\n+# repeat this a few times. There does not seem to be an option that we can pass to nix\n+# to make it retry itself.\n+for i in `seq 10`; do\n+    nix-build nix -A tools -A cached 2>&1 | tee nix_log\n+    # It should be in the last line but let’s use the last 3 and wildcards\n+    # to be robust against slight changes.\n+    if [[ $(tail -n 3 nix_log) == *\"unexpected end-of-file\"* ]]; then"
  }
]